// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset_chirps.sql

package database

import (
	"context"
)

const resetChirps = `-- name: ResetChirps :exec
DELETE FROM chirps
`

func (q *Queries) ResetChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetChirps)
	return err
}
