name: ci
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: tests
        run: go test ./...
